name: Upload Python Package to PyPI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools

    - name: Install package and testing dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .  # Install the package in editable mode
        pip install pytest

    - name: Run tests
      run: |
        pytest tests/

    - name: Build package
      run: |
        python -m build

    - name: Upload package to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
